apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: {{ .Release.Namespace }}
  name: feature-reaper
spec:
  schedule: {{ .Values.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: feature-reaper-sa
          restartPolicy: Never
          containers:
            - name: feature-reaper
              image: {{ .Values.image }}
              imagePullPolicy: IfNotPresent
              args:
                - --max-age={{ .Values.maxAge }}
