apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: feature-reaper-sa
  labels:
    app: feature-reaper
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: feature-reaper-clusterrole
  labels:
    app: feature-reaper
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["list", "delete", "get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: feature-reaper-clusterrolebinding
  labels:
    app: feature-reaper
subjects:
  - kind: ServiceAccount
    name: feature-reaper-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: feature-reaper-clusterrole
  apiGroup: rbac.authorization.k8s.io